### ISSUE TITLE
多表联查指明字段所属的表

### ISSUE THREAD

**Issue by 1764115099** [jiunx/xsqlparser#1]
没用过antlr，在多表查询的情况下，我如果想要提取出select的字段指明出自哪张表，需要在grammar里定义吗，还是解析后再处理就行呢，可否提供下思路呢。

**Comment by xvchris** [comment]
没法在grammer里定义的，应该解析后用antlr的visitor来处理，思路就是根据字段名或字段别名去访问该条sql的from节点，如果from节点是表或者关联表的话就根据别名或者数据库metadata确定表，如果是子查询的话就去找子查询的结果集的对应字段然后递归地去访问from节点

**Comment by xvchris** [comment]
> 没用过antlr，在多表查询的情况下，我如果想要提取出select的字段指明出自哪张表，需要在grammar里定义吗，还是解析后再处理就行呢，可否提供下思路呢。

这里有java代码的对应实现http://ganjiacheng.cn/article/2020/article_14_%E5%9F%BA%E4%BA%8Eantlr4%E5%AE%9E%E7%8E%B0HQL%E7%9A%84%E8%A7%A3%E6%9E%90-%E8%A1%A8%E8%A1%80%E7%BC%98%E5%92%8C%E5%AD%97%E6%AE%B5%E8%A1%80%E7%BC%98/
