### ISSUE TITLE
能否出个开发的详细教程

### ISSUE THREAD

**Issue by FlickerMi** [jiunx/xsqlparser#3]
想自己拓展一些数据源支持，如postgresql或Oceanbase.
十分感谢

**Comment by xvchris** [comment]
现在已经不做golang和antlr相关的开发了，出教程可能有点心有余而力不足。https://github.com/antlr/antlr4/blob/dev/doc/go-target.md 官方这里有详细的文档可以参考下
另外语法相关问题非常推荐《antlr4权威指南》

**Comment by xvchris** [comment]
如果使用jetbrains家的ide开发的话强烈推荐一款插件Antlr，非常好用
